# -*- coding: utf-8 -*-
"""Copy of sarcasm detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoY7qZpXOwpWqXkem3OzGMmCBCaruToB
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory



# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import seaborn as sns
import matplotlib.pyplot as plt
from urllib.parse import urlparse
from nltk.corpus import stopwords
import re
import json
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import nltk
nltk.download('stopwords')
# Load dataset
data = []

with open("sarcasm.json", "r", encoding="utf-8") as f:
    for line in f:
        data.append(json.loads(line))

# Convert to DataFrame
df = pd.DataFrame(data)

# Features and Labels
sentences = df['headline'].values
labels = df['is_sarcastic'].values

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(sentences, labels, test_size=0.2)

# Tokenization
vocab_size = 10000
max_length = 40
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

# Convert text to sequences
train_sequences = tokenizer.texts_to_sequences(X_train)
test_sequences = tokenizer.texts_to_sequences(X_test)

# Padding
train_padded = pad_sequences(train_sequences, maxlen=max_length, padding='post')
test_padded = pad_sequences(test_sequences, maxlen=max_length, padding='post')

# Build Model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 16),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Train
history = model.fit(
    train_padded,
    y_train,
    epochs=10,
    validation_data=(test_padded, y_test)
)

# Evaluate
loss, accuracy = model.evaluate(test_padded, y_test)
print("Test Accuracy:", accuracy)

# Prediction function
def predict_sarcasm(text):
    sequence = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(sequence, maxlen=max_length, padding='post')
    result = model.predict(padded)[0][0]
    
    if result > 0.5:
        print("😏 Sarcastic")
    else:
        print("🙂 Not Sarcastic")

# Test your own sentence
predict_sarcasm("Oh great, another Monday morning!")
predict_sarcasm("I love sunny days")

def predict_sarcasm(text):
    sequence = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(sequence, maxlen=max_length, padding='post')

    prediction = model.predict(padded)

    if prediction[0][0] > 0.5:
        print(f'"{text}" → 😏 Sarcastic')
    else:
        print(f'"{text}" → 🙂 Not Sarcastic')


# Test sentences
predict_sarcasm("Oh great, another Monday morning!")
predict_sarcasm("I love sunny weather")
predict_sarcasm("Wow, my internet stopped again, amazing!")